package com.example.proyectofingrado.Interfaces

interface FillCaloricTable {

    fun FillList():MutableList<String>{
        return mutableListOf(
            "Aceitunas negras\n349 calorías",
            "Aceitunas verdes\n132 calorías",
            "Acelgas\n33 calorías",
            "Ajos\n169 calorías",
            "Alcachofas\n64 calorías",
            "Apio\n20 calorías",
            "Berenjena\n29 calorías",
            "Berros\n21 calorías",
            "Brócoli\n31 calorías",
            "Calabacín\n31 calorías",
            "Calabaza\n24 calorías",
            "Cebolla\n47 calorías",
            "Cebolla tierna\n39 calorías",
            "Champiñón y otras setas\n28 calorías",
            "Col\n28 calorías",
            "Col de Bruselas\n54 calorías",
            "Coliflor\n30 calorías",
            "Endibia\n22 calorías",
            "Escarola\n37 calorías",
            "Esparragos\n 26 calorías",
            "Espárragos en lata\n 24 calorías",
            "Espinaca\n 32 calorías",
            "Espinacas congeladas\n 25 calorías",
            "Habas tiernas\n 64 calorías",
            "Hinojo\n 16 calorías",
            "Lechuga\n 18 calorías",
            "Nabos\n 29 calorías",
            "Papas cocidas\n 86 calorías",
            "Pepino\n 12 calorías",
            "Perejil\n 55 calorías",
            "Pimiento\n 22 calorías",
            "Porotos verdes\n 21 calorías",
            "Puerros\n 42 calorías",
            "Rábanos\n 20 calorías",
            "Remolacha\n 40 calorías",
            "Repollo\n 19 calorías",
            "Rúcula\n 37 calorías",
            "Soja en brotes\n 50 calorías",
            "Tomate triturado en conserva\n 39 calorías",
            "Tomates\n 22 calorías",
            "Trufa\n 92calorías",
            "Zanahoria\n 42 calorías",
            "Zumo de tomate\n calorías",
            "Arándanos\n 41 calorías",
            "Caqui\n 64 calorías",
            "Cereza\n 47 calorías",
            "Chirimoya\n 78 calorías",
            "Ciruela\n 44 calorías",
            "Ciruela seca\n 290calorías",
            "Coco\n 646 calorías",
            "Dátil\n 279calorías",
            "Dátil seco\n 306 calorías",
            "Frambuesa\n 40 calorías",
            "Fresas\n 36 calorías",
            "Granadas\n 65 calorías",
            "Grosella\n 37 calorías",
            "Higos\n 80 calorías",
            "Higos secos\n 275 calorías",
            "Kiwi\n 51 calorías",
            "Limón\n 39 calorías",
            "Mandarina\n 40 calorías",
            "Mango\n 57 calorías",
            "Manzana\n 52 calorías",
            "Melón\n 31 calorías",
            "Mora\n 37 calorías",
            "Naranja\n 44 calorías",
            "Nectarina\n 64 calorías",
            "Nísperos\n 97 calorías",
            "Papaya\n 45 calorías",
            "Pera\n 61 calorías",
            "Piña\n 51 calorías",
            "Piña en almíbar\n 84 calorías",
            "Plátano\n 90 calorías",
            "Pomelo\n 30 calorías",
            "Sandía\n 30 calorías",
            "Uva\n 81 calorías",
            "Uva pasa\n 324 calorías",
            "Zumo de naranja\n 42 calorías",
            "Almendra\n 620 calorías",
            "Avellanas\n 675 calorías",
            "Castañas\n 199 calorías",
            "Maní\n 560 calorías",
            "Nueces\n 660 calorías",
            "Piñones\n 660 calorías",
            "Pistacho\n 581 calorías",
            "Cuajada\n 92 calorías",
            "Flan de huevo\n 126 calorías",
            "Flan de vainilla\n 102 calorías",
            "Helados lácteos\n 167 calorías",
            "Leche condensada\n 350 calorías",
            "Leche de cabra\n 72 calorías",
            "Leche de oveja\n 96 calorías",
            "Leche descremada\n 36 calorías",
            "Leche en polvo entera\n 500 calorías",
            "Leche entera\n 68 calorías",
            "Leche semi descremada\n 49calorías",
            "Mousse\n 177 calorías",
            "Nata o cream de leche\n 298 calorías",
            "Queso blanco desnatado\n 70 calorías",
            "Queso Brie\n 263 calorías",
            "Queso cammembert\n 312 calorías",
            "Queso cheddar\n 381 calorías",
            "Queso crema\n 245 calorías",
            "Queso de bola\n 349 calorías",
            "Queso de Burgos\n 174 calorías",
            "Queso de oveja\n 245 calorías",
            "Queso edam\n 306 calorías",
            "Queso emmental\n 415 calorías",
            "Queso fundido untable\n 285 calorías",
            "Queso gruyere\n 391 calorías",
            "Queso manchego\n 376 calorías",
            "Queso mozzarella\n 245 calorías",
            "Queso parmesano\n 393 calorías",
            "Queso ricota\n 400 calorías",
            "Queso roquefort\n 405 calorías",
            "Requesón\n 96 calorías",
            "Yogurt desnatado\n 45 calorías",
            "Yogurt desnatado con frutas\n 82 calorías",
            "Yogurt enriquecido con nata\n 65 calorías",
            "Yogurt natural\n 62 calorías",
            "Yogurt natural con fruta\n 100 calorías",
            "Bacon\n 665 calorías",
            "Butifarra cocida\n 390 calorías",
            "Butifarra, slachicha fresca\n 326 calorías",
            "Cabrito\n 127 calorías",
            "Chuleta de cerdo\n 330 calorías",
            "Hígado de cerdo\n  153 calorías",
            "Lomo de cerdo\n 208 calorías",
            "Chicharrón\n 601 calorías",
            "Chorizo\n 468 calorías",
            "Ciervo\n 120 calorías",
            "Codorniz y perdiz\n 114 calorías",
            "Conejo y liebre\n 162 calorías",
            "Cordero lechón\n 105 calorías",
            "Pierna de cordero\n 98 calorías",
            "Costillas de cordero\n 215 calorías",
            "Hígado de cordero\n 132 calorías",
            "Faisán\n 144 calorías",
            "Foie-Gras\n 518 calorías",
            "Gallina\n 369 calorías",
            "Hamburguesa\n 230 calorías",
            "Jabalí\n 107 calorías",
            "Jamón\n 380 calorías",
            "Jamón cocido\n 126 calorías",
            "Jamón crudo\n 296 calorías",
            "Jamón York\n 289 calorías",
            "Lengua de vaca\n 191 calorías",
            "Lomo embuchado\n 380 calorías",
            "Mortadela\n 265 calorías",
            "Pato\n 200 calorías",
            "Muslo de pavo\n 186 calorías",
            "Pechuga de pavo\n 134 calorías",
            "Perdiz\n 120 calorías",
            "Pies de cerdo\n 290 calorías",
            "Hígado de pollo\n 129 calorías",
            "Muslo de pollo\n 186 calorías",
            "Pollo\n 134 calorías",
            "Salami\n 325 calorías",
            "Salchicha Frnakfurt\n 315 calorías",
            "Salchichón\n 294 calorías",
            "Ternera\n 181 calorías",
            "Chuleta de ternera\n 168 calorías",
            "Hígado de ternera\n 140 calorías",
            "Lengua de ternera\n 207 calorías",
            "Rión de ternera\n  86 calorías",
            "Sesos de ternera\n 125 calorías",
            "Solomillo de ternera\n 290 calorías",
            "Tira de asado\n 401 calorías",
            "Tripas\n 100 calorías",
            "Hígado de vacuno\n 129 calorías",
            "Almejas\n 50 calorías",
            "Anchoas\n 175 calorías",
            "Anguilas\n 200 calorías",
            "Atún en lata con aceite\n 280 calorías",
            "Atún en lata con agua\n 127 calorías",
            "Atún fresco\n 225 calorías",
            "Bacalao fresco\n 322 calorías",
            "Bacalao seco\n 322 calorías",
            "Besugo\n 118 calorías",
            "Caballa\n 153 calorías",
            "Calamar\n 82 calorías",
            "Cangrejo\n 85 calorías",
            "Caviar\n 233 calorías",
            "Congrio\n 112 calorías",
            "Dorada\n 80 calorías",
            "Gallo\n 73 calorías",
            "Gambas\n 96 calorías",
            "Langosta\n 67 calorías",
            "Langostino\n 96 calorías",
            "Lenguado\n 73 calorías",
            "Lubina\n 118 calorías",
            "Lucio\n 81 calorías",
            "Mejillón\n 74 calorías",
            "Merluza\n 86 calorías",
            "Mero\n 118 calorías",
            "Ostras\n 80 calorías",
            "Pejerrey\n  87 calorías",
            "Pez espada\n 109 calorías",
            "Pulpo\n 57 calorías",
            "Rodaballo\n 81 calorías",
            "Salmón\n 172 calorías",
            "Salmón ahumado\n 154 calorías",
            "Salmonete\n 97 calorías",
            "Sardina en lata con aceite\n 192 calorías",
            "Sardinas\n 151 calorías",
            "Trucha\n 94 calorías",
            "Azúcar\n 380 calorías",
            "Colacao\n 366 calorías",
            "Caramelos\n 378 calorías",
            "Chocolate con leche\n 550 calorías",
            "Chocolate sin leche\n 530 calorías",
            "Crema de chocolste con avellanas\n 549 calorías",
            "Dulce de membrillo\n 215 calorías",
            "Helados de agua\n 139 calorías",
            "Mermelada con azúcar\n 280 calorías",
            "Mermeladas sin azúcar\n 145 calorías",
            "Miel\n 300 calorías",
            "Arroz blanco\n 354 calorías",
            "Arroz integral\n 350 calorías",
            "Avena\n 367 calorías",
            "Cebada\n 373 calorías",
            "Centeno\n 350 calorías",
            "Cereales con chocolate\n 358 calorías",
            "Cereales con leche y miel\n 386 calorías",
            "Copos de maíz\n 350 calorías",
            "Harina de maíz\n 349 calorías",
            "Harina de trigo integral\n 340 calorías",
            "Harina de trigo refinada\n 353 calorías",
            "Pan ce centeno\n 241 calorías",
            "Pan de trigo blanco\n 255 calorías",
            "Pan de trigo integral\n 216 calorías",
            "Pan de molde blanco\n 233 calorías",
            "Pan de molde integral\n 216 calorías",
            "Pasta al huevo\n 368 calorías",
            "Pasta de sémola\n 361 calorías",
            "Polenta\n 358 calorías",
            "Sémola de trigo\n 368 calorías",
            "Yuca\n 338 calorías",
            "Garbanzos\n 361 calorías",
            "Judías\n 343 calorías",
            "Lentejas\n 336 calorías",
            "Clara\n 48 calorías",
            "Huevo duro\n 147 calorías",
            "Huevo entero\n 162 calorías",
            "Yema\n 368 calorías",
            "Bizcocho\n 456 calorías",
            "Croissant chocolate\n 469 calorías",
            "Galletas de chocolate\n 524 calorías",
            "Galletas de mantequilla\n 397 calorías",
            "Galletas saladas\n 464 calorías",
            "Magdalenas\n 469 calorías",
            "Pasta de hojaldre cocida\n 565 calorías",
            "Pastel de manzana\n 311 calorías",
            "Pastel ded queso\n 414 calorías",
            "Agua ardiente\n 280 calorías",
            "Agua tónica\n 34 calorías",
            "Anís\n 312 calorías",
            "Batido de chocolate\n 100 calorías",
            "Cacao en polvo\n 439 calorías",
            "Café\n 1 caloría",
            "Cerveza negra\n 37 calorías",
            "Cerveza rubia\n 45 calorías",
            "Champán semi-seco\n 90 calorías",
            "Champán dulce\n 118 calorías",
            "Champán seco\n 85 calorías",
            "Coñac o brandy\n 243 calorías",
            "Crema de cacao\n 260 calorías",
            "Daiquiri\n 122 calorías",
            "Gintonic\n 76 calorías",
            "Ginebra\n 244 calorías",
            "Leche de almendras\n 335 calorías",
            "Licor de caña\n 273 calorías",
            "Piña de colada\n 194 calorías",
            "Pisco\n 210 calorías",
            "Refrescos carbonatados\n 48 calorías",
            "Ron\n 244 calorías",
            "Sidra dulce\n 33 calorías",
            "Sidra seca\n 35 calorías",
            "Té\n 1 caloría",
            "Vermouth amargo\n 112 calorías",
            "Vermouth dulce\n 160 calorías",
            "Vino de mesa\n 70 calorías",
            "Vino dulce\n 160 calorías",
            "Vino oporto\n 160 calorías",
            "Vodka\n 315 calorías",
            "Whisky\n 244 calorías",
            "Aceite de girasol\n 900 calorías",
            "Aceite de oliva\n 900 calorías",
            "Manteca\n 670 calorías",
            "Mantequilla\n 752 calorías",
            "Margarina vegetal\n 752 calorías",
            "Bechamel\n 115 calorías",
            "Caldos concentrados\n 259 calorías",
            "Ketchup\n 98 calorías",
            "Mayonesa\n 718 calorías",
            "Mayonesa light\n 374 calorías",
            "Mostaza\n 15 calorías",
            "Salsa de soja\n 61 calorías",
            "Salsa de tomate en conserva\n 86 calorías",
            "Sofrito\n 116 calorías",
            "Vinagres\n 8 calorías",

        )

    }
}